version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/frontend/PyBet"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"