# Generated by Django 5.1.4 on 2025-01-26 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPickedOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("selectedOption", models.CharField(max_length=255)),
                ("date", models.DateField()),
                ("selectedOdds", models.FloatField()),
                ("stake", models.FloatField()),
            ],
        ),
    ]
