# Generated by Django 5.1.4 on 2025-01-28 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0002_userpickedoption"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraccount",
            name="pycoins",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="userpickedoption",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="server.useraccount",
            ),
        ),
    ]
