# Generated by Django 5.1.4 on 2024-12-29 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0002_useraccount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useraccount",
            name="email",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
