# Generated by Django 5.1.4 on 2024-12-29 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("server", "0003_alter_useraccount_email"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Login",
        ),
        migrations.AddField(
            model_name="useraccount",
            name="groups",
            field=models.ManyToManyField(
                blank=True, related_name="useraccount_set", to="auth.group"
            ),
        ),
        migrations.AddField(
            model_name="useraccount",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="useraccount",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="useraccount",
            name="is_superuser",
            field=models.BooleanField(
                default=False,
                help_text="Designates that this user has all permissions without explicitly assigning them.",
                verbose_name="superuser status",
            ),
        ),
        migrations.AddField(
            model_name="useraccount",
            name="last_login",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="last login"
            ),
        ),
        migrations.AddField(
            model_name="useraccount",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True, related_name="useraccount_set", to="auth.permission"
            ),
        ),
        migrations.AlterField(
            model_name="useraccount",
            name="email",
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="useraccount",
            name="password",
            field=models.CharField(max_length=128, verbose_name="password"),
        ),
    ]
