# Generated by Django 5.1.4 on 2025-01-29 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0003_useraccount_pycoins_userpickedoption_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpickedoption",
            name="matchTeams",
            field=models.CharField(max_length=25, null=True),
        ),
    ]
