name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install
        working-directory: frontend/PyBet

      - name: Lint code
        run: npm run lint
        working-directory: frontend/PyBet

      - name: Type-check code
        run: npm run type-check
        working-directory: frontend/PyBet

      - name: Run unit tests
        run: npm run test
        working-directory: frontend/PyBet

      - name: Generate code coverage report
        run: npm run test:coverage
        working-directory: frontend/PyBet

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/*.json
          flags: unittests
          name: codecov-umbrella
        working-directory: frontend/PyBet

      - name: Build project
        run: npm run build
        working-directory: frontend/PyBet

  e2e:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install
        working-directory: frontend/PyBet

      - name: Build project
        run: npm run build
        working-directory: frontend/PyBet

      - name: Run end-to-end tests
        run: npm run test:e2e
        working-directory: frontend/PyBet

      - name: Generate code coverage report for E2E tests
        run: npm run test:e2e:coverage
        working-directory: frontend/PyBet

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/*.json
          flags: e2etests
          name: codecov-umbrella
        working-directory: frontend/PyBet