name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install --prefix frontend

      - name: Lint code
        run: npm run lint --prefix frontend

      - name: Type-check code
        run: npm run type-check --prefix frontend

      - name: Check code formatting
        run: python3 scripts/format-cli.py js ts vue json html css py --check

      # - name: Run unit tests
      #   run: npm run test --prefix frontend/PyBet

      # - name: Generate code coverage report
      #   run: npm run test:coverage --prefix frontend/PyBet

      # - name: Upload coverage to Codecov
      #   uses: codecov/codecov-action@v3
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }}
      #     files: frontend/PyBet/coverage/*.json
      #     flags: unittests
      #     name: codecov-umbrella

      - name: Build project
        run: npm run build --prefix frontend

  # e2e:
  #   runs-on: ubuntu-latest
  #   needs: build

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3

  #     - name: Set up Node.js
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: '18'

  #     - name: Cache Node.js modules
  #       uses: actions/cache@v3
  #       with:
  #         path: ~/.npm
  #         key: ${{ runner.os }}-node-${{ hashFiles('frontend/PyBet/package-lock.json') }}
  #         restore-keys: |
  #           ${{ runner.os }}-node-

  #     - name: Install dependencies
  #       run: npm install --prefix frontend/PyBet

  #     - name: Run end-to-end tests
  #       run: npm run test:e2e --prefix frontend/PyBet

  #     - name: Generate code coverage report for E2E tests
  #       run: npm run test:e2e:coverage --prefix frontend/PyBet

  #     - name: Upload coverage to Codecov
  #       uses: codecov/codecov-action@v3
  #       with:
  #         token: ${{ secrets.CODECOV_TOKEN }}
  #         files: frontend/PyBet/coverage/*.json
  #         flags: e2etests
  #         name: codecov-umbrella